// src/data/projectManagementData.js

export const projectsData = [
  {
    id: 'p1',
    name: 'Bridge Construction Project',
    description:
      'Design and construction of a 4-lane river bridge with modern engineering standards and safety protocols.',
    status: 'active',
    assignedTo: ['Ali', 'Sara', 'Mike'],
    startDate: '2025-01-10',
    endDate: '2025-06-30',
    progress: 40,
    priority: 'high',
  },
  {
    id: 'p2',
    name: 'Highway Expansion',
    description:
      'Widening existing highway to support increased traffic flow and improve transportation efficiency.',
    status: 'on-hold',
    assignedTo: ['Bilal'],
    startDate: '2024-11-01',
    endDate: '2025-09-15',
    progress: 25,
    priority: 'medium',
  },
  {
    id: 'p3',
    name: 'Metro Station Upgrade',
    description:
      'Structural and electrical upgrade of metro stations including accessibility improvements.',
    status: 'completed',
    assignedTo: ['Team A', 'Team B'],
    startDate: '2024-05-01',
    endDate: '2024-12-01',
    progress: 100,
    priority: 'low',
  },
];

export const tasksData = [
  {
    id: 'T-001',
    projectId: 'p1',
    name: 'Implement authentication system',
    project: 'Bridge Construction Project',
    assignee: 'John Doe',
    status: 'In Progress',
    priority: 'High',
    dueDate: '2025-12-15',
  },
  {
    id: 'T-002',
    projectId: 'p2',
    name: 'Design landing page mockups',
    project: 'Highway Expansion',
    assignee: 'Jane Smith',
    status: 'In Progress',
    priority: 'Medium',
    dueDate: '2025-12-10',
  },
  {
    id: 'T-003',
    projectId: 'p1',
    name: 'Setup CI/CD pipeline',
    project: 'Bridge Construction Project',
    assignee: 'Bob Johnson',
    status: 'Pending',
    priority: 'High',
    dueDate: '2025-12-20',
  },
  {
    id: 'T-004',
    projectId: 'p3',
    name: 'Write API documentation',
    project: 'Metro Station Upgrade',
    assignee: 'Alice Williams',
    status: 'Completed',
    priority: 'Low',
    dueDate: '2025-11-30',
  },
  {
    id: 'T-005',
    projectId: 'p2',
    name: 'Database schema optimization',
    project: 'Highway Expansion',
    assignee: 'John Doe',
    status: 'In Progress',
    priority: 'Medium',
    dueDate: '2025-12-18',
  },
];

export const subtasksData = [
  {
    id: 'ST-001',
    taskId: 'T-001',
    name: 'Setup OAuth providers',
    assignee: 'John Doe',
    status: 'In Progress',
    priority: 'High',
    dueDate: '2025-12-12',
    progress: 60,
  },
  {
    id: 'ST-002',
    taskId: 'T-001',
    name: 'Create login UI components',
    assignee: 'Jane Smith',
    status: 'Completed',
    priority: 'Medium',
    dueDate: '2025-12-08',
    progress: 100,
  },
  {
    id: 'ST-003',
    taskId: 'T-002',
    name: 'Design hero section',
    assignee: 'Jane Smith',
    status: 'In Progress',
    priority: 'High',
    dueDate: '2025-12-09',
    progress: 75,
  },
  {
    id: 'ST-004',
    taskId: 'T-003',
    name: 'Configure GitHub Actions',
    assignee: 'Bob Johnson',
    status: 'Pending',
    priority: 'High',
    dueDate: '2025-12-18',
    progress: 0,
  },
  {
    id: 'ST-005',
    taskId: 'T-004',
    name: 'Create API endpoints documentation',
    assignee: 'Alice Williams',
    status: 'Completed',
    priority: 'Low',
    dueDate: '2025-11-28',
    progress: 100,
  },
];

export const goalsData = [
  {
    id: 'G-001',
    name: 'Launch MVP by Q1 2026',
    description: 'Complete core platform features and deploy to production',
    owner: 'John Doe',
    status: 'On Track',
    progress: 65,
    startDate: '2025-10-01',
    targetDate: '2026-03-31',
    relatedProjectIds: ['p1', 'p2'],
  },
  {
    id: 'G-002',
    name: 'Achieve 95% test coverage',
    description: 'Implement comprehensive unit and integration tests',
    owner: 'Bob Johnson',
    status: 'On Track',
    progress: 78,
    startDate: '2025-11-01',
    targetDate: '2025-12-31',
    relatedProjectIds: ['p1', 'p3'],
  },
  {
    id: 'G-003',
    name: 'Onboard 50+ beta users',
    description: 'Build user base for beta testing program',
    owner: 'Jane Smith',
    status: 'At Risk',
    progress: 42,
    startDate: '2025-11-15',
    targetDate: '2026-01-15',
    relatedProjectIds: ['p2'],
  },
  {
    id: 'G-004',
    name: 'Optimize page load to <2s',
    description: 'Improve application performance metrics',
    owner: 'Alice Williams',
    status: 'Completed',
    progress: 100,
    startDate: '2025-09-01',
    targetDate: '2025-11-30',
    relatedProjectIds: ['p3'],
  },
];
